### ISSUE TITLE
Memory leak in client.getValue

### ISSUE THREAD

**Issue by Mikmak2000** [ubidots/ubidots-esp8266#25] opened 2017-08-12 20:55 UTC
Using the client.getValue function will cause the ESP to reboot after 50+ runs.
It seems that there is no free() in client.getValue but it is there in the other getValue functions.

**Comment by mariacarlinahernandez** [comment] 2017-08-14 20:47
Hello @Mikmak2000,

Effectively, the method produce a memory leak into the board, I was missing the `free(data)` in the method. The issue is already fixed in the following PR #26

Please @woakas, review the PR to merge and solve the issue.

**Closed as completed** 2017-08-14 21:43 UTC
